name: Run Test

on:
  push:
    branches: ["**"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0

      - name: Setup node
        uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38

      - name: Install pnpm
        uses: pnpm/action-setup@b0f76dfb45f55f8421693e4803ac7bb65143bd34

      - name: Install dependencies
        run: pnpm install

      - name: Run test
        run: |
          pnpm typecheck
          pnpm lint
          pnpm knip
          pnpm test:ci
